# Generated by Django 4.2.9 on 2025-12-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='developers/'),
        ),
    ]
